#!/bin/bash
## Description of script goes here

#PBS -S /bin/bash		
#PBS -l walltime=24:00:00	## specify maximum wall time
#PBS -l nodes=1:ppn=6		## number of nodes, and number of processors per node (max 16)
#PBS -l mem=5gb			## n-1 = GB of memory for each job. Defualt is 4GB. Total memory of all jobs cannot exceed 12*4=64GV
## PBS -m bea			## send email at beginning (b), end (e) of job or when it aborts (a)
## PBS -M rw9g11@soton.ac.uk	## specify email(s) to send to


cd $PBS_O_WORKDIR 		## Iridis runs from home directory by default. This means it will run from the current directory.

## executable lines below here

module load cplex

DATE_TIME=$(date +%Y%m%d-%H%M%S)
echo >> result_log.txt
echo -n  $DATE_TIME >> result_log.txt
## ampl -x 10000 rand_init.mod constraints.mod rand.dat multiple_solve.run | tee  results/multiple_$DATE_TIME.txt
ampl -x 100000 init.mod constraints.mod data.dat multiple_solve.run>/home/rw9g11/VRP/results/multiple_$DATE_TIME.txt
echo -n '	trivial' >> result_log.txt
echo $DATE_TIME
